server:
  port: 8090

spring:
  application:
    name: student-record
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_assign1
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost